name: 🧪 Check backend

on:
  push:
    paths:
      - backend/**
      - .github/workflows/check-backend.yaml

defaults:
  run:
    working-directory: backend

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v4.0.2
        with:
          aqua_version: v2.53.9
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: task lint
